//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SinuosityCore.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SinuosityCore.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /GeoProperties/County Shapefile/Field.
        /// </summary>
        internal static string Config_ShapeFile_Field_County {
            get {
                return ResourceManager.GetString("Config_ShapeFile_Field_County", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /GeoProperties/Ecoregion Code Shapefile/Field.
        /// </summary>
        internal static string Config_ShapeFile_Field_EcoregionCode {
            get {
                return ResourceManager.GetString("Config_ShapeFile_Field_EcoregionCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /GeoProperties/HUC Watershed Code Shapefile/Field.
        /// </summary>
        internal static string Config_ShapeFile_Field_HUCWatershedCode {
            get {
                return ResourceManager.GetString("Config_ShapeFile_Field_HUCWatershedCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /GeoProperties/HUC Watershed Name Shapefile/Field.
        /// </summary>
        internal static string Config_ShapeFile_Field_HUCWatershedName {
            get {
                return ResourceManager.GetString("Config_ShapeFile_Field_HUCWatershedName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /GeoProperties/L3 Ecoregion Name Shapefile/Field.
        /// </summary>
        internal static string Config_ShapeFile_Field_L3Ecoregion {
            get {
                return ResourceManager.GetString("Config_ShapeFile_Field_L3Ecoregion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /GeoProperties/L4 Ecoregion Name Shapefile/Field.
        /// </summary>
        internal static string Config_ShapeFile_Field_L4Ecoregion {
            get {
                return ResourceManager.GetString("Config_ShapeFile_Field_L4Ecoregion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /GeoProperty/State Shapefile/Field.
        /// </summary>
        internal static string Config_ShapeFile_Field_State {
            get {
                return ResourceManager.GetString("Config_ShapeFile_Field_State", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /GeoProperties/County Shapefile/Path.
        /// </summary>
        internal static string Config_ShapeFile_Path_County {
            get {
                return ResourceManager.GetString("Config_ShapeFile_Path_County", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /GeoProperties/Ecoregion Code Shapefile/Path.
        /// </summary>
        internal static string Config_ShapeFile_Path_EcoregionCode {
            get {
                return ResourceManager.GetString("Config_ShapeFile_Path_EcoregionCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /GeoProperties/HUC Watershed Code Shapefile/Path.
        /// </summary>
        internal static string Config_ShapeFile_Path_HUCWatershedCode {
            get {
                return ResourceManager.GetString("Config_ShapeFile_Path_HUCWatershedCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /GeoProperties/HUC Watershed Name Shapefile/Path.
        /// </summary>
        internal static string Config_ShapeFile_Path_HUCWatershedName {
            get {
                return ResourceManager.GetString("Config_ShapeFile_Path_HUCWatershedName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /GeoProperties/L3 Ecoregion Name Shapefile/Path.
        /// </summary>
        internal static string Config_ShapeFile_Path_L3Ecoregion {
            get {
                return ResourceManager.GetString("Config_ShapeFile_Path_L3Ecoregion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /GeoProperties/L4 Ecoregion Name Shapefile/Path.
        /// </summary>
        internal static string Config_ShapeFile_Path_L4Ecoregion {
            get {
                return ResourceManager.GetString("Config_ShapeFile_Path_L4Ecoregion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /GeoProperty/State Shapefile/Path.
        /// </summary>
        internal static string Config_ShapeFile_Path_State {
            get {
                return ResourceManager.GetString("Config_ShapeFile_Path_State", resourceCulture);
            }
        }
    }
}
